### PR TITLE
fix for nock compatibility regarding callback being invoked twice

### PR DESCRIPTION
**Pull request by samouri**
This is a fix for one of the common cases of the double-callback issue
#417
#313

### CODE REVIEW

**Comment by focusaurus** [comment]
How about reproducing the issue in a unit test and thus verifying the fix?

**Comment by pornel** [comment]
We already have a check that prevents callback from being called twice:

https://github.com/visionmedia/superagent/blob/master/lib/node/index.js#L575

which is exactly what prints "double callback", because the message is not a bug, but a diagnostic that warns about presence of other logic bugs.

So bypassing "double callback" check doesn't fix multiple callbacks, it just hides them.

**Comment by samouri** [comment]
@pornel, what is the desired behavior in this situation:
1. client of request library creates a new request with various params
2. client calls .end()
2.1 within .end(), there is an error with adding a the query params.  This causes the callback to be called: https://github.com/visionmedia/superagent/blob/master/lib/node/index.js#L642-L659
2.2 The http request created in end() throws an error.  As things are now this will cause the callback to be called again: https://github.com/visionmedia/superagent/blob/master/lib/node/index.js#L531-L540

**Comment by pornel** [comment]
I'm afraid nock changes behavior here significantly. 

In superagent this sitation can't happen, because the request is made _after_ `_appendQueryString`, so it can't fire an error, because it's not started yet until end of the function: https://github.com/visionmedia/superagent/blob/86921996137a40b6fa12d343ca0d32daa2993fc6/lib/node/index.js#L844

**Comment by samouri** [comment]
So let me make sure I understand this correctly: 
Superagent would never run into this normally because _Node.js_'s [Http.ClientRequest](https://nodejs.org/api/http.html#http_class_http_clientrequest) does _not_ emit errors until the request has been started (`flushHeaders`, `write`, `end`, etc. has been called).

For this I agree that nock should not emit errors until one of the request-starting functions have been called. I'll open up a thread with them on the topic.

But in terms of superagent handling requests -- wouldn't it make sense to protect against this sort of issue (clients directly accessing the request object or tampering with it somehow like in the case of nock) by clearing listeners to `req` any time `superagent.end` aborts mid-way (like in this case of [errors adding query string](https://github.com/visionmedia/superagent/blob/86921996137a40b6fa12d343ca0d32daa2993fc6/lib/node/index.js#L656))

**Comment by pornel** [comment]
You're correct.

And yes, it sounds like a good idea to remove listeners (or maybe not even add them at that point yet) if something goes wrong in the setup.

**Comment by pornel** [comment]
I think moving appendQueryString (but not its catch) to inside `.request()` before handlers are attached would solve the problem, and remove some duplication.

**Comment by samouri** [comment]
I looked into it and it would break superagent functionality.  Usually people can call `.query` multiple times before sending out a request and each new query gets appended.    The way `appendQueryString` is right now, it is meant to be a final mutator.  It will only append if there is no querystring yet.

**Comment by pornel** [comment]
We did some refactoring since, and this change is still not what we want, so I'm closing this.

**Pull request closed without merging**
