### PR TITLE
Added authentication with client certificates.

### PR DESCRIPTION
**Pull request by terusus**
Client certificate authentication is a very common functionality and this PR finally provides the needed options to superagent.

https://nodejs.org/api/https.html#https_https_request_options_callback

### CODE REVIEW

**Comment by terusus** [comment]
I have no idea why one of the jobs is failing (browser=1). Any ideas?

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: connection refused: localtunnel.me:35378 (check your firewall settings)
    at Socket.<anonymous> (/home/travis/build/visionmedia/superagent/node_modules/zuul/node_modules/zuul-localtunnel/node_modules/localtunnel/client.js:84:32)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1269:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
make[1]: *** [test-browser] Error 1
make[1]: Leaving directory `/home/travis/build/visionmedia/superagent'
make: *** [test] Error 2
npm ERR! Test failed.  See above for more details.
```

**Comment by pornel** [comment]
Thank you!

**Comment by terusus** [comment]
My pleasure. Waiting for the next release.

**Comment by terusus** [comment]
Also, I believe it's safe to decline this PR: https://github.com/visionmedia/superagent/pull/681
With the TLS options provided as an object one can override all options in the request.

**Comment by pornel** [comment]
Thanks

**Comment by nathanbrock** [comment]
Hey! This pull request is incredibly useful, many thanks @terusus. Appreciate there's a lot on, but is there by any chance a time frame for the release of these additions into NPM @pornel?

**Comment by niftylettuce** [comment]
v5.1.1 released that resolves this issue

**Pull request merged**
