### PR TITLE
fixes #629. client: better handling of arrays in query parameters

### LINKED ISSUE #629: Handle arrays as query parameter?
Say I need a function that works like this:

```javascript
getThings(['a', 'b', 'c'], cb)  // GET "/things?thing[]=a&thing[]=b&thing[]=c"
```

Currently, I have to do this:

```javascript
function getThings(things, cb) {
    var req = superagent.get('/things')
    for (var i = 0; i < things.length; i++) {
        req.query({thing: things[i]});
    }
    req.end(cb);
}
```

I would like to be able to do something like this instead:

```javascript
function getThings(things, cb) {
    superagent.get('/things')
       .query({thing: things})
       .end(cb);
}
```

Alternatively, use a different name for the array-enabled query method:

```javascript
function getThings(things, cb) {
    superagent.get('/things')
       .queryArray('thing', things)
       .end(cb);
}
```

Or is there a way to do this already, that I haven't found?

### PR DESCRIPTION
**Pull request by edazdarevic**

### CODE REVIEW

**Comment by adnanh** [comment]
:+1:

**Comment by AdnanHidic** [comment]
:+1:

**Comment by defunctzombie** [comment]
What is the behavior on the server for the equivalent?

**Comment by pornel** [comment]
This has been fixed by another PR.

**Pull request closed without merging**
