### PR TITLE
support OPTIONS requests in client #544

### PR DESCRIPTION
**Pull request by greensk**
Allows to send queries with OPTIONS HTTP method

### CODE REVIEW

**Comment by focusaurus** [comment]
Could you grab the tests I added from [this commit on my fork](https://github.com/focusaurus/superagent/commit/1d8562bf1dfff312c8d8eb7be46c46a108d98754) and rebase your PR including the test code?

From a feature perspective, this looks good to me. I confirmed at least in Chrome the browser happily sends OPTIONS requests and includes the body.

@greensk I'd be curious to hear your specific use case and motivation for adding this feature.

**Comment by rafaelugolini** [comment]
:+1:

**Comment by greensk** [comment]
> Could you grab the tests I added from this commit on my fork and rebase your PR including the test code?
@focusaurus, done.

> I'd be curious to hear your specific use case and motivation for adding this feature
OPTIONS queries are used to fetch data schema from REST API. Sorry, I am not able to show you my code example, it is proprietary.

**Comment by rafaelugolini** [comment]
@focusaurus I also use OPTIONS method to fetch data schema. The forms of the application I'm working on are generated through calls using the OPTIONS method.

**Comment by pornel** [comment]
LGTM. We'll merge it after releasing 1.8.1, since we've got a small fix to release first

**Comment by focusaurus** [comment]
@pornel I think we could merge this and roll into a semver minor 1.9 release or for 2.0 which it seems like we are getting close to ready to release.

**Comment by OmgImAlexis** [comment]
This really should have changes to the docs included in the PR.

**Pull request merged**
