### PR TITLE
add generator docs

### PR DESCRIPTION
**Pull request by matthewmueller**
Okay added some docs for generators. I wasn't sure what `markdown`:

img

is being referred to here. I don't have that lib installed. But here are some docs. They'll need to be rebuilt.

### CODE REVIEW

**Comment by defunctzombie** [comment]
Something about how this works via the `.then` function would help folks if they run into issues.

**Comment by focusaurus** [comment]
LGTM. Should be OK to merge. No release needed.

**Comment by focusaurus** [comment]
@olalonde @pornel another one we should be able to quickly review and merge.

**Comment by pornel** [comment]
Thanks

**Pull request merged**
