### PR TITLE
saucelabs browser test tweaks

### PR DESCRIPTION
**Pull request by focusaurus**
- 20s timeouts
- latest zuul
- configure SAUCE_APPIUM 1.6

I was seeing our 10s timeouts exceeded a lot in sauce labs for slower browsers/OSes. Increasing to 20s seems empirically to help. :-/

### CODE REVIEW

**Comment by focusaurus** [comment]
Well, most of the sauce browser tests actually passed. The one that failed has:

```
<internet explorer 10 on Windows 2012> request :: on 303 :: should redirect with same method
Error: Unable to get property 'text' of undefined or null reference (http://jhpwkkjpxw.localtunnel.me/__zuul/test-bundle.js:10232)
```

Which I would think means localtunnel failed to serve the test-bundle properly.

**Comment by focusaurus** [comment]
Maybe let's try focusaurus.com (a domain I bought just to run localtunnel-server in a docker container after realizing localtunnel-server only works on top-level hostnames), at least for a while to see if there really are reliability problems with localtunnel.me

**Comment by pornel** [comment]
That's great. Thank you.

**Comment by pornel** [comment]
And it's cool that there are still .com domains available :)

**Pull request merged**
