### PR TITLE
fix `delete` breaking on ie8

### PR DESCRIPTION
**Pull request by kenjiokabe**
Please check if mergeable.

I want to use this nice library on Ie8 with no error...
(I know it supports `>=ie9`)

Thank you.

### CODE REVIEW

**Comment by pornel** [comment]
Does it work apart from this?

**Comment by kenjiokabe** [comment]
@pornel 
Yes, it works!

cf. 
http://stackoverflow.com/questions/26479123/angularjs-http-delete-breaks-on-ie8

**Comment by kenjiokabe** [comment]
@pornel 
Thank you for merging!

Could you please update npm ver. `1.6.1` -> `1.6.2` ?

**Comment by lbeschastny** [comment]
:+1: It would be very nice to have this PR released

**Pull request merged**
