### PR TITLE
enable secure protocol

### PR DESCRIPTION
**Pull request by muddydixon**
I want to request "TLS1" server.
So add `Request.prototype.secureProtocol` method.

### CODE REVIEW

**Comment by muddydixon** [comment]
Please merge me!

**Comment by defunctzombie** [comment]
what does this do?

**Comment by muddydixon** [comment]
by this p-r, we can control ssl/tsl version to request.
(now I want to connect a server only accepting tls1 protocol.)

**Comment by defunctzombie** [comment]
What about the client version?

**Comment by muddydixon** [comment]
i forked from v1.2.0 (exactly 94afa3ae189267a8d352d72b20edb9900148959e).

**Comment by defunctzombie** [comment]
Not sure what that last comment has to do with this. I was asking about the browser side version of the library.

**Comment by muddydixon** [comment]
Sorry, I use superagent in node (ServerSide).

**Comment by defunctzombie** [comment]
While that may be the case, we still need to keep parity between the two versions if we can. Is this feature relevant for the client version?

**Comment by muddydixon** [comment]
I don't know it, but I will check it.

**Comment by kornelski** [comment]
This is no longer compatible, so I'm going to close this.

**Pull request closed without merging**
