### PR TITLE
emit 'GET' progress event

### PR DESCRIPTION
**Pull request by Autarc**
Trigger the progress event for GET requests in the browser.

### CODE REVIEW

**Comment by defunctzombie** [comment]
This may have the downside of triggering a CORS preflight in some browsers.

https://bugzilla.mozilla.org/show_bug.cgi?id=727412

I think we should only connect progress handler if the user adds a progress listener in their app. Otherwise we should avoid using the upload listeners.

**Comment by eyeofhell** [comment]
Thanks for update! Actually, it will trigger CORS in all browsers since this behavior is required by specs. If some browser doesn't trigger CORS it's probably something very old or not standard-compliant

**Comment by defunctzombie** [comment]
Cannot merge because it will trigger CORS in browsers and users may not want that.

**Comment by Autarc** [comment]
The main issue was the missing handler for emitting progress updates on GET request to resources. Although you omit the one for uploads, perhaps you could still add this one for larger downloads.

**Pull request closed without merging**
