### PR TITLE
README - query string

### PR DESCRIPTION
**Pull request by oprogramador**

### CODE REVIEW

**Comment by focusaurus** [comment]
It's not clear to me why the plugin example needs updating this way. Perhaps you did not encounter `docs/index.md` which powers the main superagent website and documentation?

**Comment by oprogramador** [comment]
I think it's an essential example and it should be in README.md (at least `query`).

**Comment by pornel** [comment]
Query example seems like a good thing to add.

While we're at it, could we have an example with some realistic values, not "foo" and "some-url"?

**Comment by oprogramador** [comment]
@pornel I updated this PR.

**Comment by pornel** [comment]
Great! thank you

**Pull request merged**
