### PR TITLE
fixed #696

### LINKED ISSUE #696: this.xhr.getResponseHeader('content-type') returns empty with react-native >0.5
I have been struggling with why all my apis start to fail after upgrading to `react-native` 0.5 and above. What I found is that, after upgrading `getResponseHeader('content-type')` returns null.

refer #181

### PR DESCRIPTION
**Pull request by alinz**
added some code to check `getResponseHeader('content-type'…)` prior to set to `content-type`

### CODE REVIEW

**Comment by defunctzombie** [comment]
don't understand the issue here. If the content-type header is null then the null value will be set to `this.headers[content-type]`. Alternatively you just don't set the value. Both seem like essentially the same behavior, no?

**Comment by alinz** [comment]
hmm, what I found was, [parseHeader](https://github.com/visionmedia/superagent/blob/master/lib/client.js#L304) parse the header correctly which contains `application/json` but we are blindly trusted [this.xhr.getResponseHeader('content-type');](https://github.com/visionmedia/superagent/blob/master/lib/client.js#L308) and override the `content-type`. So in my PR, I check the return value of `this.xhr.getResponseHeader('content-type')` first, before overriding the `content-type`.

**Comment by defunctzombie** [comment]
#696 sounds like a react-native bug to me. Why does it not return the correct value for getResponseHeader? Seems like if it worked as expected for that method then there would be no issue.

**Comment by alinz** [comment]
Agreed, however, do you think it's a good idea to overriding header's `content-type` without checking the `xhr.getResponseHeader`'s value?

**Comment by defunctzombie** [comment]
Kinda since one would reasonable expect that function to return the header value or null based on the docs: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#getResponseHeader()

**Comment by focusaurus** [comment]
I'm going to close this as #696 has been closed and the maintainers have not been compelled to merge after almost 8 months. If this is still an issue for you with the latest react-native, maybe follow up with that project. Thanks for your effort, though!

**Pull request closed without merging**
