### PR TITLE
Avoiding to set the "Content-Length" header for GET requests

### PR DESCRIPTION
**Pull request by marcellobarile**
PR for #1459

### CODE REVIEW

**Comment by marcellobarile** [comment]
tests on Travis seems to randomly fail. All tests pass on local.

**Comment by niftylettuce** [comment]
@marcellobarile I'd love to get this added to v5.x release which just came out.  Do you think you could add it?  You'll have to modify `src/node/index.js` instead of `lib/node/index.js` (see latest `master` branch).

**Comment by marcellobarile** [comment]
sure, I'll do that. Thanks @niftylettuce

**Comment by marcellobarile** [comment]
@niftylettuce seems that tests on travis are still randomly failing; I'm not sure if it's strictly related to this PR though. Do you have any clue?

**Comment by niftylettuce** [comment]
@marcellobarile I unfortunately had to revert this change.

Please see my comment here https://github.com/visionmedia/superagent/commit/804c35c781d0e8768e16d9f4265260863f7
0cb0a#r33084161

The tests are failing due to your PR

**Comment by marcellobarile** [comment]
yup, saw that. I will retouch it asap.

**Pull request merged**
