### PR TITLE
Use `res.getHeaders()` to avoid deprecation warning

### PR DESCRIPTION
**Pull request by ad-m**
See #1502

### CODE REVIEW

**Comment by thw0rted** [comment]
This isn't the only place where _headers is referenced, just look down a few lines in the file you changed.  See my comments on the linked issue for more details, but the short version is your patch won't work.

**Comment by thw0rted** [comment]
Also: on L509 and L522, I think the `headers =` is extraneous.  The method returns a reference to its first parameter, which is going to have to be `headers` anyway, so the assignment will do nothing.

**Comment by niftylettuce** [comment]
Do we need tests added?

**Comment by ad-m** [comment]
Rebased to build on Node 12. Added ```--throw-deprecation``` to fail, when deprecated method used.

**Comment by ad-m** [comment]
Is there anything what I can do to help merge that PR?

**Comment by busticated** [comment]
hi all :wave:

thanks for all the work in pulling this together and maintaining this lib over the years :pray::bow:

fwiw, this is blocking formal `node@12` support over in https://github.com/particle-iot/particle-cli (see [failing tests here](https://travis-ci.org/particle-iot/particle-cli/jobs/617502392#L1047)).

i'd be happy to pitch in w/ additional fixes and / or testing as you see fit 👍

**Comment by niftylettuce** [comment]
v5.1.2 is released to npm and everything should be fine wit latest versions of Node now 🎉 	

If you find any further deprecation warnings in the future please let me know!

```sh
npm install superagent@latest
```

or with yarn:

```sh
yarn add superagent@latest
```

https://github.com/visionmedia/superagent/releases/tag/v5.1.2

**Pull request merged**
