### PR TITLE
add jspm support

### PR DESCRIPTION
**Pull request by u9520107**
add jspm dependencies and main configuration in package.json to support jspm package manager uses

### CODE REVIEW

**Comment by defunctzombie** [comment]
Don't see the benefit in this over existing tools that read what is already in package.json.

**Comment by u9520107** [comment]
@defunctzombie So if I use jspm as client-side package manager, I have no other choice than to fork the project and add those properties in my fork?

**Comment by defunctzombie** [comment]
@u9520107 yes. I think that all of the relevant metadata is already in package.json and other package managers make us of that information. It would be unwise to throw every custom package manager tidbit into the package file since everyone has their favorite. As far as I am aware webpack and browserify work with the format we are using.

**Comment by u9520107** [comment]
@defunctzombie Ok, thx. I suspect that jspm should support the "browser" property. Might be a bug that it's not currently working. I'll go probe around jspm's issues.

**Pull request closed without merging**
