### PR TITLE
add sortQuery function

### PR DESCRIPTION
**Pull request by vicanso**
sort query string for HTTP accelerator, such as varnish, instead of #839

### CODE REVIEW

**Comment by focusaurus** [comment]
Would `sortQuery` be a better name in terms of English grammar verb object?

**Comment by vicanso** [comment]
@focusaurus I have changed `querySort` to `sortQuery `

**Comment by focusaurus** [comment]
LGTM. Semver-Minor. @pornel thoughts?

**Comment by pornel** [comment]
`'function' == typeof this._sort` is overengineered. `.sortQuery(false)` doesn't disable sorting.

**Comment by focusaurus** [comment]
I rebased this code and addressed Pornel's comments. The tests now pass and there's documentation. It's in my fork here: https://github.com/focusaurus/superagent/tree/sort-query

@vicanso The rebase lost your commit author metadata. You may want to take the final diff between my sort-query branch and master, make a single new feature commit, and then PR that in. I think we should be able to accept the PR then unless @pornel has any further reservations.

**Comment by pornel** [comment]
Regarding git, instead of committing, you need to run `git rebase --continue` to preserve authorship. You can fix this with `git commit --amend --author="user <email>"`.

As for the code, I don't see the point of using is-function module instead of `'function' === typeof`. From what I gather it's a workaround for old browsers confusing regexes with functions, none of which applies here.

**Comment by pornel** [comment]
rebased as 07147ce74ccc4a87388593c68b2d8a94d3d0bc41

**Pull request closed without merging**
