### PR TITLE
Extend .npmignore with few extra things which do not need to be published

### PR DESCRIPTION
**Pull request by pkuczynski**
The smaller the package the faster the download :)

### CODE REVIEW

**Comment by pkuczynski** [comment]
@niftylettuce any feedback on this PR?

**Comment by niftylettuce** [comment]
Could we just make this mirrored to the `.gitignore` of projects like https://github.com/cabinjs/cabin or https://github.com/ladjs/lad?  I think there's too much bloat in here.

**Comment by pkuczynski** [comment]
@niftylettuce sure. Here you go: https://github.com/cabinjs/cabin/pull/147 https://github.com/ladjs/lad/pull/418

**Comment by pkuczynski** [comment]
@niftylettuce how about this PR? Can you approve it and merge it?

**Comment by niftylettuce** [comment]
`yarn.lock` should be committed to the repo

**Comment by pkuczynski** [comment]
This is about `.npmignore` not `.gitignore`. So after this PR is merged, `yarn.lock` will be still committable, but not published to npm. Make sense?

**Comment by niftylettuce** [comment]
Closed in favor of https://github.com/visionmedia/superagent/pull/1667

**Pull request closed without merging**
