### PR TITLE
Add .dataFilter function prior to parsing of body

### PR DESCRIPTION
**Pull request by tquetano-r7**
This function allows you to transform the data prior to parsing of the body. It attempts not to be opinionated on the type of data or what you are trying to do to it. The basic application:
```
request
  .get('url.com/foo')
  .dataFilter((data) => {
    return data.replace(/text_to_strip/g, '');
  })
  .end((err, res) => {
    console.log(res.body); // will have text_to_strip removed globally from the data
  });
```
The original application I was striving for was stripping of XSS prefixes / postfixes, however I tried to make it more generalized so that it could be used for a multitude of purposes. This method is only applied in the parseBody function, and if nothing is returned from the callback passed then it falls back to the original str value passed to parseBody.

Apologies in advance for the lack of commit squashing.

### CODE REVIEW

**Comment by tquetano-r7** [comment]
Apologies again, I have no easy way to produce a test for this locally as I don't have saucelabs credentials and therefore cannot do the BROWSER=1 test. Based on another client test, I modified to see if this would work. I promise I have tested it in the real world ...

**Comment by pornel** [comment]
You can run tests without saucelabs with `make test-browser-local`

**Comment by tquetano-r7** [comment]
@pornel Thanks, that is some badassery. I ran that locally and all my tests passed, and I know my travis build failed but I don't think it was due to my test.

**Comment by pornel** [comment]
Yeah, travis tests are sometimes a bit flaky and need restarting.

**Comment by tquetano-r7** [comment]
Ah sweet, noticed the browser test was kicked off again and passed, I assume that was you. :)

**Comment by focusaurus** [comment]
I would prefer not to add more API surface for this. Is this not reasonably achievable already with `request.parse['application/json'] = stripPrefixes`?

In either case this would need consistency in the node/client code before merging.

**Comment by tquetano-r7** [comment]
Going about it in the way you recommended appears to solve my issue. Thanks!

**Pull request closed without merging**
