### PR TITLE
Skip null querystring values in node environment.

### PR DESCRIPTION
**Pull request by Gerhut**
In order to match the behavior of browser environment.

### CODE REVIEW

**Comment by pornel** [comment]
Thanks. Consistency is definitely desirable. However, maybe we should adjust browser to match node instead?

`JSON.stringify` keeps `null`s:

```js
JSON.stringify({n:null,u:undefined})
'{"n":null}'
```

**Comment by Gerhut** [comment]
I prefer ignoring them because `{"a": null}` compiles `a=`, which may not be decided with `{"a": ""}`.

**Comment by pornel** [comment]
Query string taking JSON isn't meant to preserve it 100% (for that you'd use actual JSON post type), it's just a convenience. I think it's fine as long as it's consistent and seems sensible.

Perhaps we could serialize `{a:null,b:1}` as `?a&b=1`.

**Comment by pornel** [comment]
@focusaurus what do you think about it?

**Comment by focusaurus** [comment]
I like your suggestion of `{a:null,b:1}` encodes to `?a&b=1`. That seems reasonable.

More broadly, I dislike informal serialization schemes that try to map nested objects and arrays into a query string since they tend to be poorly-defined and have broken edge cases. If I were to rethink the superagent API I might explicitly limit `.query(foo)` to a single non-nested object of names and scalar values.

**Comment by pornel** [comment]
Thank you @Gerhut!

**Pull request merged**
