### PR TITLE
Wrapped parse call into try/catch block

### PR DESCRIPTION
**Pull request by yunda**
This commit resolves situation when server response holds something like "Forbidden".

### CODE REVIEW

**Comment by focusaurus** [comment]
Could you add a unit test, please? Otherwise seems reasonable to me.

**Comment by yunda** [comment]
This pull-request supposed to fix #675

**Comment by pornel** [comment]
This is a breaking change

**Comment by pornel** [comment]
Returning of unparsed string is dangerous, e.g. let's say the server used to return `{accessDenied: false}` or `Forbidden!`

```js
.end(err, res) {
   if (err || res.body.accessDenied) return;
   allowAccess();
}
```

with this change `res.body` would be "Forbidden!" and `res.body.accessDenied` would be `undefined` and evaluate to falsy value, causing a security issue.

**Comment by yunda** [comment]
@pornel The idea is to return a response even if it fails to parse body. Otherwise we cannot read status codes or any other necessary information form the response object.

**Comment by pornel** [comment]
@yunda you can from the error object, that's what rawResponse was for.

**Comment by pornel** [comment]
@yunda now there's `err.statusCode`. Do you need to read other properties during an error?

**Comment by pornel** [comment]
I'm closing in favor of `err.rawResponse` and `err.statusCode`, which I think are safer and more backwards-compatible.

**Pull request closed without merging**
