### PR TITLE
track recent merges in the History.md

### PR DESCRIPTION
**Pull request by focusaurus**

### CODE REVIEW

**Comment by olalonde** [comment]
Might be too big of a change right now but if we used a [standardised format](https://github.com/ajoslin/conventional-changelog/blob/master/conventions/angular.md) for commit messages, we could use [conventional-recommended-bump](https://github.com/stevemao/conventional-recommended-bump) to do semantic versioning for us and [conventional-changelog](https://github.com/ajoslin/conventional-changelog/) to generate `History.md`.

I use the following scripts in my own projects:

```javascript
{ "scripts": {
    "preversion": "npm test && npm run changelog",
    "version:auto": "npm version $(conventional-recommended-bump --preset=angular)",
    "postversion": "git push && git push --tags",
    "release": "npm run version:auto && npm publish",
    "prepublish": "npm run build",
    "changelog:generate": "conventional-changelog -p angular -i CHANGELOG.md -w",
    "changelog:commit": "git add CHANGELOG.md && git commit -m \"chore(changelog): auto generate changelog\"",
    "changelog": "npm run changelog:generate && npm run changelog:commit"
}}
```

**Comment by focusaurus** [comment]
I'm +1 on more tooling, but down the road after we clear the backlog of PRs/issues. For the next few weeks/months as we work the backlog, I think it's more important to work PRs/issues and not get bogged down with "hey can you resubmit this PR with a comment in this magic format?".

**Comment by olalonde** [comment]
Agreed.

> "hey can you resubmit this PR with a comment in this magic format?"

Haha yeah, that's one downside of this approach.

**Comment by pornel** [comment]
Sorry, I haven't noticed you've updated history, so I've made a conflicting commit.

**Comment by pornel** [comment]
(I've used `git log --format='%s (%an)'`)

**Pull request closed without merging**
