### PR TITLE
Added highlighting to the documentation menu

### PR DESCRIPTION
**Pull request by eligolding**
This PR uses Bootstrap's ScrollSpy plugin to highlight the menu options in the docs as you scroll into each section, making it easier to know which section of the docs you are in.
I also updated jQuery to the latest version, which was necessary for the plugin.

### CODE REVIEW

**Comment by defunctzombie** [comment]
index.html is generated with from index.md file in the docs folder so editing it directly will just get your changes destroyed on next rebuild. You want to look at head.html

Also not against moving to a new system for docs like `slate` or something else.

**Comment by eligolding** [comment]
Thanks. Didn't realize it worked like that.

**Comment by focusaurus** [comment]
@eligolding can you rework this change to reflect this conversation and re-submit? If not I'll recommend closing this as minor and stale.

**Comment by eligolding** [comment]
Sorry been meaning to get back to this for while. I'll try to work on this asap. If I can't get something working soon I'll close this.

**Comment by eligolding** [comment]
I just push a new commit. This one uses the [tocify](http://gregfranko.com/jquery.tocify.js/#) jquery plugin to generate the documentation menu. It includes scroll highlighting and animations.
I made the proper changes to `head.html`.
I also needed to include the widget component from jqueryui.

**Comment by focusaurus** [comment]
OK, this looks good to me now. I tested locally. @pornel recommend merge on this one.

**Comment by eligolding** [comment]
Thank you!

**Pull request merged**
