### PR TITLE
Support unix sockets

### PR DESCRIPTION
**Pull request by kanreisa**
related: https://github.com/visionmedia/superagent/issues/779

I've implemented it. maybe this is not breaking change.

### CODE REVIEW

**Comment by pornel** [comment]
Thanks for the PR, but that is a hack.

I think it's inappropriate to use `http:` URL scheme for something that is not true HTTP over TCP/IP. `unix` is not a special, reserved hostname.

Python uses `http+unix` scheme for this: https://pypi.python.org/pypi/requests-unixsocket/ which seems more appropriate and avoids ambiguity.

**Comment by kanreisa** [comment]
@pornel Thanks review, I've fixed.

**Comment by pornel** [comment]
That's better. Thanks! Can you add tests to ensure we don't break it?

**Comment by kanreisa** [comment]
@pornel yes, added :cake:

**Comment by philpill** [comment]
@kanreisa is this PR the cause of the current build failure?Is anyone looking into it?

**Comment by kanreisa** [comment]
retry build please

**Comment by pornel** [comment]
I've restarted the build

**Comment by kanreisa** [comment]
Oops, Node.js 0.10 has failed. I'll check it later.

**Comment by philpill** [comment]
Sorry, I added the comment about the failing build a bit earlier, but removed it as I'm not sure if this PR (or the work for this PR) was the cause.

**Comment by pornel** [comment]
Have you checked node 0.10? If there's no simple fix for it I don't mind disabling the feature in node 0.10 (i.e. detect node 0.10 in tests and skip the tests).

**Comment by pornel** [comment]
Since 0.10 life [ends this month](https://github.com/nodejs/LTS#lts_schedule) we can go ahead and merge this.

**Pull request merged**
