### PR TITLE
request-base: add header for inspect

### PR DESCRIPTION
**Pull request by magicdawn**
header is also important for inspect a request. as I'm using the `Authentication` header for auth. and I'm using this

```js
request
  .get(url)
  .set('foo', 'bar')
  .then((err, res) => {
    if(err) return next(err);
  });
```

`next` is the `next` in express. I'd like to inspect the header too.

### CODE REVIEW

**Comment by pornel** [comment]
Should it be `header` or `headers`?

**Comment by magicdawn** [comment]
@pornel That's a question ...

**Comment by pornel** [comment]
In node it's `headers`, so I suggest going with that: https://nodejs.org/api/http.html#http_message_headers

Also, could you add a basic unit test for it?

**Comment by magicdawn** [comment]
Oops ...

**Comment by pornel** [comment]
Thank you

**Pull request merged**
