### PR TITLE
Adding statusCode to error response when JSON response is malformed

### PR DESCRIPTION
**Pull request by mattdell**
In reference to issue #876, these changes will allow the client to access the http status code even when the JSON response body is malformed.

### CODE REVIEW

**Comment by mattdell** [comment]
The travis build seems to have passed but timed out on the last step. Could someone with write access give it a nudge?

**Comment by pornel** [comment]
Thank you! 

@focusaurus ?

**Comment by pornel** [comment]
I'm going to rebase it to remove unnecessary commits.

**Comment by mattdell** [comment]
Thanks @pornel, that would be greatly appreciated!

**Comment by mattdell** [comment]
I was curious how to do that @pornel and have figured it out. Another PR raised here with just the single commit: https://github.com/visionmedia/superagent/pull/878

**Pull request closed without merging**
