### PR TITLE
Added 'progress' event on file/form upload in Node

### PR DESCRIPTION
**Pull request by olalonde**
See issue #516

### CODE REVIEW

**Comment by olalonde** [comment]
Hmmm any feedback? Is this project still maintained?

**Comment by focusaurus** [comment]
@olalonde see #785 for updates on transitions to new maintainers.

LGTM. Recommend merge and semver minor bump.

**Comment by pornel** [comment]
How do you distinguish between upload and download progress? Won't it confuse existing code that posts something and then expects to track *download* progress?

I don't see `lengthComputable` changed anywhere. 

Are you certain Content-Length is always available?

**Comment by olalonde** [comment]
> How do you distinguish between upload and download progress? Won't it confuse existing code that posts something and then expects to track download progress?

Curiously, the browser implementation doesn't seem to distinguish between upload/download: https://github.com/visionmedia/superagent/blob/master/lib/client.js#L974 

Maybe we should address this first?

> I don't see lengthComputable changed anywhere.

Yes it's not changed. I just put it there so that the event object somewhat resembles what browser progress events: http://dev.w3.org/2006/webapi/progress/Progress.html

AFAIK, Content-Length is always available when using form data. There is actually a [TODO](https://github.com/olalonde/superagent/blob/node-progress-event/lib/node/index.js#L1010) which explicitly states that "unknown length" uploads aren't supported yet.

**Comment by pornel** [comment]
Great, thank you!

**Comment by shishirx34** [comment]
This is great. Thank you for getting this merged in. @pornel, any idea when the next npm update will be available for these changes on superagent?

**Pull request merged**
