### PR TITLE
Disable setting default user-agent

### LINKED ISSUE #1479: how to avoid sending user-agent header?
In [unirest](https://github.com/Kong/unirest-nodejs), when I don't specify `user-agent` header, it's just not sent. However `superagent` sends `node-superagent/5.0.2`.

`.set('user-agent', undefined)` fails with `TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "user-agent"`

`.set('user-agent', '')` sends `{ 'user-agent': '' }`

`.set('user-agent', null)` sends `{ 'user-agent': 'null' }`

### PR DESCRIPTION
**Pull request by apoorv-mishra**
Fixes #1479

### CODE REVIEW

**Comment by niftylettuce** [comment]
Can you please fix the tests @apoorv-mishra?

**Comment by apoorv-mishra** [comment]
> Can you please fix the tests @apoorv-mishra?

@niftylettuce I have a bit of difficulty here. I assumed that we would need to remove tests which test for setting default `user-agent`. Tests for that are in `test/node/user-agent.js`. I removed it and ran `npm run build && npm run lint && make test`. Still tests seem to fail. What should be done here?

**Comment by apoorv-mishra** [comment]
@niftylettuce Updated.

**Comment by niftylettuce** [comment]
I've released this as v5.1.0 to npm, it has a minor version bump because existing users may have issues with the user-agent being stripped in this version.

`npm install superagent@latest`

https://github.com/visionmedia/superagent/releases/tag/v5.1.0

**Comment by wyardley** [comment]
IMHO, this would have been better as a breaking / major change.
Certain sites (GitHub, for example) will reject requests sent without a `User-Agent` header.

**Comment by comster** [comment]
> IMHO, this would have been better as a breaking / major change.
> Certain sites (GitHub, for example) will reject requests sent without a `User-Agent` header.

For instance this does break https://github.com/lambtron/get-stargazers-emails - FWIW

**Pull request merged**
