### PR TITLE
Resolve IE issue that cannot understand arrow function

### PR DESCRIPTION
**Pull request by jsveron23**
screenshot 2019-03-05 at 11 31 22 am

- IE 11 cannot understand arrow function

### CODE REVIEW

**Comment by shankie-san** [comment]
@jsveron23 do you have this issue just with `getXHR`? For me, IE also fails here:

https://github.com/visionmedia/superagent/blob/1724997edc451df62139385266d17438002d918f/lib/agent-base.js#L6

**Comment by shankie-san** [comment]
As a workaround, I've modified my webpack config to exclude superagent from my node_modules exclusions (if that makes sense!) using this https://github.com/webpack/webpack/issues/2031#issuecomment-219040479

**Comment by jsveron23** [comment]
@shankie-san This is not about makes sense, I think. Normally, most people ignore transpile JS inside `node_module` directory. Because of improving performance. And mostly, node packages normally, already transpiled. So, those solution is fine. I found this package does not support ES2015~ for IE as native Javascript way. So, I have no idea this PR is ok for them.

**Comment by niftylettuce** [comment]
I will be publishing a new version soon that is compiled for older browser support (last 2 versions and > 1%).

**Comment by shankie-san** [comment]
👍 @niftylettuce

**Comment by shankie-san** [comment]
@niftylettuce if you think of it, if you could post back here once that's published, that would be great – as other people will come to this issue if they've searched Google for "superagent arrow functions"

**Comment by niftylettuce** [comment]
I commented everywhere else here in this GH repo but this issue (my bad!), v5.0.0 was released last night! @shankie-san.

---

v5.0.0 was just released to NPM and an updated README is now available here on GitHub (see <https://github.com/visionmedia/superagent#superagent>).

## What's new

* Browser version is now only 19KB (that's 60% in file size savings from v4.x which was 48KB)!
* Codebase refactored using `xo`, `prettier`, `remark`, and more
* Browser compatibility linting via `eslint-plugin-compat`
* Browserslist integration (current targets are `> 1%, last 2 versions, ie 9`)

## How to install

```sh
npm install superagent@latest
```

> Or if you're using yarn:

```sh
yarn add superagent@latest
```

## Polyfills

Please see the [Required Browser Features](https://github.com/visionmedia/superagent#required-browser-features) section in the README if you plan to support IE 9 and/or IE 10 and use `superagent`.

**Comment by shankie-san** [comment]
Great thanks for letting me know @niftylettuce

**Comment by lorenzos** [comment]
I still have arrow functions from superagent in my build, I'm using `5.0.2`. How's that? I'm using browserify, for some reason it's using source files instead of the ones in `dist/`...

**Comment by niftylettuce** [comment]
Please share your complete configuration - the easiest way for us to help you is to create a repository on GitHub that we can clone locally and reproduce this issue.

**Comment by lorenzos** [comment]
@niftylettuce I made a super simple private repo, and grant you access: <https://github.com/lorenzos/superagent-demo-1465/invitations>. Just clone and run `npm install && npm run build`, and you will se in `build/build.js` the superagent source file with all the arrows functions.

**Comment by niftylettuce** [comment]
See my comment here: https://github.com/visionmedia/superagent/issues/1470#issuecomment-481007403

**Comment by lorenzos** [comment]
@niftylettuce Thanks for your many comments explaining the issue and explaining why superagent works differently from other packages. I'll try to configure Babelify so that it transforms superagent files in `node_modules`, i.e. using `global: true; ignore: /\/node_modules\/(?!superagent\/)/`. Thanks.

**Pull request closed without merging**
