### PR TITLE
keep upload alive for large files or slow connections

### PR DESCRIPTION
**Pull request by DenisVuyka**
Addresses issue #1374

Keeps upload alive for very large files or slow connections, resets deadline/timeout timers while data is still being sent over the wire.

I have tested the fix with network throttling using Chrome DevTools, also tested on a real project. However I cannot find a way to create a unit test that has slow upload with progress updates simulated.

### CODE REVIEW

**Comment by kornelski** [comment]
Thank you for the PR. However, I don't think that's appropriate. 

I see what you want — monitoring whether connection is still alive and timing out only after data stops flowing. That would be useful. But that's not what current timers are supposed to do. The deadline's main purpose *is* to kill slow connections, even if they're still going. 

If you can accept the upload taking half an hour, then you can't set the deadline (or you have to set it to half an hour).

The `_responseTimeoutTimer` is cleared in readyState change >= 2, which is fired when headers are received. Its not set again, so doesn't need to be cleared later.

So if you'd like to implement watchdog timer for connection stalling, then you need to add a third timer. Don't cancel the existing ones.

**Comment by DenisVuyka** [comment]
I see what you mean, thanks. Will try to increase timeout settings at the client side.

**Comment by eromano** [comment]
@kornelski also if we add a third timer the deadline timeout will be still active . 
Should I just disable the deadline timeout and other this third timeout?

**Comment by kornelski** [comment]
No, don't touch the other options. They are independent.

**Comment by kornelski** [comment]
From what I understand, you are setting the deadline timer, which sole purpose is to unconditionally abort the request, and then you don't like that the timer fires and unconditionally aborts the request.

There's nothing wrong with the deadline timer, it does exactly what it's supposed to do. It's just not a feature for you, so *don't use it*. Don't call `.timeout({deadline:…})`. 

> How can I avoid the deadline timeout to happen if I don't clear it?

You can't avoid the timer if it's already been set. By design supposed to be unconditional. If you change the implementation to clear the timer in some circumstances, then you just break that feature.

What I'm suggesting is that you add a third kind of timer, completely separate from the other two, and then:

* Do not set the deadline, at all. Never. Just forget it ever existed.
* Use the third kind of timer.

In that situation you don't need to clear the deadline timer.

**Comment by eromano** [comment]
Ok I got it, thanks.
This timer will works only if the deadline timer is not set or it's value is minor of the deadline.
Do you would like to have this functionality in superagent or is better that we just overwrite it in our side?

**Comment by kornelski** [comment]
Yes, this functionality (timeout since last bit of data was sent or received) would be useful in superagent. Here's previous discussion of that feature: #1115

I've just remembered we've had reports that the upload events are buggy in some browsers: #1244 #840 

So this is going to be a serious problem for uploads, and will require special handling (e.g. find a way to detect when the browser fires events for buffering rather than actual sending, or support the timeout only in browsers tested and verified to work).

**Comment by eromano** [comment]
Ok thanks , I guess I will try to create a PR but I will sure need your help

**Comment by kornelski** [comment]
Sure! I'm happy to help.

**Pull request closed without merging**
