### PR TITLE
675: Return raw response if the parsing fails

### PR DESCRIPTION
**Pull request by reinaldo13**
This commit includes:
- Fix for #675
- Test to verify the code change.

### CODE REVIEW

**Comment by focusaurus** [comment]
@reinaldo13 this looks good on the client side. Could you add another commit making the corresponding change to the server side code with a test as well?

**Comment by reinaldo13** [comment]
@focusaurus: sure! Not a problem. I can get this done within the next couple of days.

**Comment by reinaldo13** [comment]
@focusaurus: i just added the corresponding change to the server side code + test. Feel free to review when you get a chance. Thanks!

**Comment by pornel** [comment]
Well done. Thank you.

**Pull request merged**
