### PR TITLE
Use query instead of send for HEAD requests

### PR DESCRIPTION
**Pull request by acontreras89**
As per [my comment](https://github.com/visionmedia/superagent/issues/534#issuecomment-297592130) on issue #534.

I don't know if you'll be willing to accept such change, but it didn't require much effort.

### CODE REVIEW

**Comment by focusaurus** [comment]
Should we make the corresponding change to [the node side](https://github.com/focusaurus/superagent/blob/master/lib/node/index.js#L931) as well?

**Comment by acontreras89** [comment]
@focusaurus I'm not familiar with the node implementation of this. I took a look but it seems it's already treating GET and HEAD requests the same way, even though they are not treated as in the browser version.

**Comment by kornelski** [comment]
We've done this in ce2f27d5

**Comment by acontreras89** [comment]
:clap:

**Pull request closed without merging**
