### PR TITLE
Update dev deps

### PR DESCRIPTION
**Pull request by pornel**
Relaxed version requirements for dev deps, since it can't break production and we have CI.

### CODE REVIEW

**Comment by focusaurus** [comment]
These are failing due to saucelabs not being able to start up one of the environments:

```
Error: [init({"build":"724","name":"superagent","tags":
[],"browserName":"iphone","version":"9.2","platform":"Mac 10.10","appium-version":"1.3.6"})] The 
environment you requested was unavailable.: {"status": 13, "sessionId": 
"7421609f14fa4e0c9fcc88e67c6383e2", "value": {"message": "The Sauce VMs failed to start the 
browser or device\nFor more info, please check https://docs.saucelabs.com/reference/troubleshooting-
common-error-messages"}}
```

Can we disable that environment or somehow get a more reliable process?

**Comment by pornel** [comment]
It might be a flaky VM or an actual incompatibility caught by the test. I'm going to restart the test later to see.

**Comment by focusaurus** [comment]
The way I read the error message seems to mean "we couldn't get an environment started at all" thus I don't think they even ran any code in this case.

**Comment by pornel** [comment]
It has worked with Zuul 3.

**Pull request merged**
