### PR TITLE
support for use inside webworker

### PR DESCRIPTION
**Pull request by lucidNTR**
there is no window object inside webworkers

### CODE REVIEW

**Comment by tnrich** [comment]
Hey there, is anything stopping these changes being merged in? I need them to use superagent in a webworker.

**Comment by tadjik1** [comment]
Yep, merge it please.

**Comment by defunctzombie** [comment]
Why is this different from: https://github.com/visionmedia/superagent/pull/673

And neither have tests.

**Comment by lucidNTR** [comment]
both are the same, i did not see the other pull request due to its generic description.
the other version is probably better because using self can be better handled by linters.

**Pull request closed without merging**
