### PR TITLE
fixes #670 - handles arrays better

### LINKED ISSUE #670: arrays in query parameter are handled differently in node vs browser libraries
`.query({ hello: ['a', 'b', 'c'] })`

returns different things
node:
`?hello=a&hello=b&hello=c` (correct)

browser:
`?hello=a,b,c` (incorrect)

### PR DESCRIPTION
**Pull request by davis**
a different format from #629 

I believe the option for array formatting should be eventually exposed to the user a la qs:

```js
Qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'indices' })
// 'a[0]=b&a[1]=c' 
Qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'brackets' })
// 'a[]=b&a[]=c' 
Qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'repeat' })
// 'a=b&a=c' 
```

### CODE REVIEW

**Comment by pornel** [comment]
This brings client-side implementation in line with the server-side one (which supports arrays already). LGTM @focusaurus?

**Comment by focusaurus** [comment]
There seems to be several issues and PRs about this issue. I need some time to review and come up to speed before I can confidently make a recommendation. In particular, #699 includes tests.

**Comment by pornel** [comment]
I like this implementation better. I'm going to take this code, and tests from the other PR. OK?

**Comment by focusaurus** [comment]
Sure. I haven't looked at these in detail yet so if you have, go for it.

**Comment by davis** [comment]
sweet! thanks guys

**Pull request merged**
