### PR TITLE
ES6 Promise support

### LINKED ISSUE #722: The .then() function is not compatible with Promises
The faux `.then()` function added in 1.3 completely misses the point of promises and breaks even in simple cases.

```js
request.get(someCorrectUrl)
    .then(function(){return 1;})
    .then(console.log.bind(console));
```
Should print `1`, but throws an unhandled exception.

```js
request.get('fail').then(function(){});
```
> TypeError: reject is not a function

```js
request.get('fail')
    .then(undefined, function(){throw Error();})
    .catch(function(){})
```
> .then(...).catch is not a function

Please don't try to reimplement promises — just enable use of a correct library.

I suggest:

```js
Request.prototype.then = function(resolve, reject) {
  var self = this;
  return new Promise(function(resolve, reject){
    self.end(function(err, res){
      if (err) reject(err); else resolve(res);
    });
  })
  .then(resolve, reject);
};
```

The code above assumes that promises are either supported natively (already the case in majority of browsers and even Node 0.12) or polyfilled by the user (which is a common practice, e.g. ES6 transpilers do it).

### PR DESCRIPTION
**Pull request by pornel**
Fixes #722

### CODE REVIEW

**Comment by kahnjw** [comment]
This addresses my compatibility concerns by adding a thenable fallback, but is weird/unexpected from a behavioral standpoint.

Also, I'd suggest returning a promise from the `.end()` method if there is community support for it. Having the `then` method fire the request is arbitrary and weird. If the goal is to use real promises, we should use promises as they were intended - then methods should not perform actions other than to return a new promise. You could also add a new function `.endPromise()`, or something like that to address backward compatibility concerns.

**Comment by pornel** [comment]
I agree returning promise from `end()` would be better.

I also think it should cache the promise, so that `var tmp = superagent.get(); tmp.then(); tmp.then()` doesn't try to launch the request again.

**Comment by pornel** [comment]
BTW: the code for both node and browser happens to be identical. Do you have a preferred way for sharing/reusing it?

**Comment by euwest** [comment]
>I also think it should cache the promise, so that var tmp = superagent.get(); tmp.then(); tmp.then() doesn't try to launch the request again.

Yeah, which is further reason for `end` returning the promise and it not being a part of `then`(maybe that's what you were saying?). That way you'd have:
```js
var tmp = superagent.get().end();

tmp.then(); 
tmp.then();
```

**Comment by defunctzombie** [comment]
I am gonna say it again. I do not care about supporting promises in this library. The `.then` hack was to make it a simple thenable and I was fine with that. If you want a promise then use a wrapper.

Yes, we need to document the `.then` call better.

**Comment by vire** [comment]
What's the status please, there is an closed PR, but in the latest version of superagent (v1.4.0 and node v0.12.7) is not working as expected (see #722).

**Comment by FoxxMD** [comment]
@vire It was closed but not merged. @defunctzombie said above that he will not support A+ promises

**Comment by vire** [comment]
@FoxxMD thanks for clarification. It's a pity indeed to not be complaint with some standard approach.

**Comment by euwest** [comment]
>It's a pity indeed to not be comlpaint with some standard approach.

Superagent is not a promises implementation, though. Request objects just have a `then` method to make it a little easier to coerce into a promise, given an actual implementation.

**Comment by niftylettuce** [comment]
Here's a promise implementation (uses ES6/ES7 async/await too, with ES6's new `fetch()` method) https://github.com/glazedio/frisbee.

**Pull request closed without merging**
