### PR TITLE
Set xhr.response instead of xhr.responseText to err.rawResponse

### PR DESCRIPTION
**Pull request by kolodoz**
responseText throws InvalidStateError when responseType is not 'text' or ''

### CODE REVIEW

**Comment by pornel** [comment]
IIRC `.response` is an XHR2 feature, which IE9 does not support.

**Comment by kolodoz** [comment]
Sorry, forgot about our old friend. Fixed and added a test.

**Comment by kolodoz** [comment]
Missed the button

**Comment by focusaurus** [comment]
LGTM. @pornel should we merge this?

**Pull request merged**
